# method / detaset / arch / pretrained
method: "kl"
dataset: "imagenet"

# optimization settings: https://github.com/pytorch/vision/tree/main/references/classification#resnet
optim: "sgd"
lr: 0.001
lr_scheduler_type: "cosine"
momentum: 0.9
weight_decay: 0.0001
nesterov: True
batch_size: 32
seed: 0
epoch: 1

lr_warmup_type: 'linear'
lr_warmup_decay: 0.03
lr_warmup_epoch: 0
amp: True

# wandb flag
#enable_wandb: false

print_freq: 1000